// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdNZr-dpBp3dGO7BzZPy2W9TlZmHj8uZM',
    appId: '1:763353680196:web:55a48f9aa6e9095dd7ef11',
    messagingSenderId: '763353680196',
    projectId: 'hassanat-418712',
    authDomain: 'hassanat-418712.firebaseapp.com',
    storageBucket: 'hassanat-418712.appspot.com',
    measurementId: 'G-2EJ03DV5WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu84y95-QbRbEBs468fWAdJNPtXNVGj58',
    appId: '1:763353680196:android:0a7b8a9c138a66dbd7ef11',
    messagingSenderId: '763353680196',
    projectId: 'hassanat-418712',
    storageBucket: 'hassanat-418712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcNSOMAoyqRyZHp6lutReDMJowXjUKcWI',
    appId: '1:763353680196:ios:8f27c8d4d05a3da8d7ef11',
    messagingSenderId: '763353680196',
    projectId: 'hassanat-418712',
    storageBucket: 'hassanat-418712.appspot.com',
    iosBundleId: 'com.example.hasanat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcNSOMAoyqRyZHp6lutReDMJowXjUKcWI',
    appId: '1:763353680196:ios:1f1cdc223380f0d7d7ef11',
    messagingSenderId: '763353680196',
    projectId: 'hassanat-418712',
    storageBucket: 'hassanat-418712.appspot.com',
    iosBundleId: 'com.example.hasanat.RunnerTests',
  );
}
